### ISSUE TITLE
Missing .ui files

### ISSUE THREAD

**Issue by paulmueller** [Mega-hertzzz/Raman-Spectroscopy-Data-analysis-Software-MCR-ALS#1]
Hi,
it would be helpful if you could add the original .ui files that you used to create the GUI (assuming that you used QtDesigner for that).

General Comment: To make code maintenance easy, it is not a good idea to use the code generated with `pyuic5`, but instead load and use the .ui files in the scripts.

**Comment by Mega-hertzzz** [comment]
Hi,

Thank you for your comment.

First I created an initial GUI using QtDesigner, then I developed it in the script.
I uploaded that initial .ui file under PARS_v1.2.2a directory.

**Comment by paulmueller** [comment]
Thank you!
